FROM ubuntu:latest

COPY ssh-key/id_rsa.pub /root/.ssh/authorized_keys
COPY bin/startup.sh /startup.sh

RUN apt update -y && \
    apt install -y openssh-server && \
    mkdir -p -m0755 /var/run/sshd && \
    chmod 700 /root/.ssh &&\
    chmod 600 /root/.ssh/authorized_keys && \
    sed -i "s|#Port|Port|g" /etc/ssh/sshd_config && \
    sed -i "s|#PubkeyAuthentication|PubkeyAuthentication|g" /etc/ssh/sshd_config && \
    sed -i "s|#AuthorizedKeysFile|AuthorizedKeysFile|g" /etc/ssh/sshd_config && \
    chmod +x /startup.sh

CMD ["/startup.sh"]
